# Core data: substances, medication classes, personal factors, mechanism templates.
# Language: English, international brand names only.

SUBSTANCES = [
    {"id": "alcohol", "name": "Alcohol", "aliases": ["beer", "wine", "spirits", "booze"], "cat": "depressant",
     "base": ["Dehydrates and impairs judgement; the most common co-ingestant in every festival incident."]},
    {"id": "cannabis", "name": "Cannabis (THC)", "aliases": ["weed", "marijuana", "hash", "joint", "edibles"], "cat": "other",
     "base": ["Edibles hit late (1–2 h) — redosing is the classic mistake. Panic/greening-out responds to calm, sugar, quiet."]},
    {"id": "mdma", "name": "MDMA", "aliases": ["ecstasy", "molly", "XTC", "pills", "mandy"], "cat": "stimulant",
     "base": ["Overheating and hyponatremia are the main killers: cool-down breaks, sip ~500 ml/h of electrolyte drink — do NOT push large volumes of plain water."], "tpl": ["HYPERTHERMIA", "CARDIO"]},
    {"id": "amphetamine", "name": "Amphetamine / Meth", "aliases": ["speed", "meth", "crystal", "whizz", "base"], "cat": "stimulant",
     "base": ["Cardiovascular strain, no sleep, no food; psychosis risk rises with sleep deprivation."], "tpl": ["CARDIO", "PSYCH"]},
    {"id": "cocaine", "name": "Cocaine", "aliases": ["coke", "crack", "blow"], "cat": "stimulant",
     "base": ["Short action invites redosing; chest pain in a cocaine user is a medical emergency until proven otherwise."], "tpl": ["CARDIO"]},
    {"id": "ketamine", "name": "Ketamine", "aliases": ["ket", "special K", "K"], "cat": "dissociative",
     "base": ["Falls and airway risk in a k-hole: get them seated/lying somewhere safe, recovery position if unresponsive."]},
    {"id": "lsd", "name": "LSD", "aliases": ["acid", "tabs", "blotter", "trip"], "cat": "psychedelic",
     "base": ["Psychological support > medication for a difficult trip: calm sitter, quiet space, grounding."], "tpl": ["PSYCH"]},
    {"id": "mushrooms", "name": "Psilocybin mushrooms", "aliases": ["shrooms", "magic mushrooms", "psilocybin"], "cat": "psychedelic",
     "base": ["As LSD: difficult experiences are managed with calm presence, not drugs."], "tpl": ["PSYCH"]},
    {"id": "2c-x", "name": "2C-B / 2C-x", "aliases": ["2CB", "nexus", "tucibi"], "cat": "psychedelic",
     "base": ["Steep, unpredictable dose–response; treat unknown pills/powders as high-potency."], "tpl": ["PSYCH", "CARDIO"]},
    {"id": "ghb", "name": "GHB / GBL", "aliases": ["G", "liquid ecstasy"], "cat": "depressant",
     "base": ["Extremely steep dose curve — 0.5 ml can separate high from coma. Never combined with alcohol. Sudden deep sleep = monitor breathing continuously."], "tpl": ["CNSDEP"]},
    {"id": "nitrous", "name": "Nitrous oxide", "aliases": ["laughing gas", "balloons", "whippits"], "cat": "dissociative",
     "base": ["Main acute risk is falling / brief blackout — do it sitting down."]},
    {"id": "dxm", "name": "DXM", "aliases": ["dextromethorphan", "cough syrup", "robo"], "cat": "dissociative",
     "base": ["Strongly serotonergic dissociative hiding in cough medicine; interacts badly with most antidepressants."], "tpl": ["SS"]},
    {"id": "mephedrone", "name": "Mephedrone / cathinones", "aliases": ["meow meow", "4-MMC", "bath salts", "3-MMC"], "cat": "stimulant",
     "base": ["Compulsive redosing pattern; strong cardiovascular + serotonergic load."], "tpl": ["CARDIO", "SS"]},
    {"id": "opioids-rec", "name": "Opioids (non-prescribed)", "aliases": ["heroin", "fentanyl", "oxy", "opium"], "cat": "depressant",
     "base": ["Respiratory depression kills; pinpoint pupils + unresponsive + slow breathing = give naloxone if your team carries it, call emergency services."], "tpl": ["CNSDEP"]},
    {"id": "benzos-rec", "name": "Benzodiazepines (non-prescribed)", "aliases": ["xanax", "bars", "benzos", "valium"], "cat": "depressant",
     "base": ["Fake pressed bars may contain potent analogues or fentanyl; blackouts and disinhibition."], "tpl": ["CNSDEP"]},
    {"id": "synth-cann", "name": "Synthetic cannabinoids", "aliases": ["spice", "K2", "JWH", "fake weed", "herbal blend"], "cat": "other",
     "base": ["Nothing like natural THC in the field: potency swings wildly between batches — seizures, psychosis, heart strain and sudden collapse all happen. Treat any 'weed that behaves strangely' as a possible synthetic."], "tpl": ["SEIZURE", "PSYCH", "CARDIO"]},
    {"id": "kratom", "name": "Kratom", "aliases": ["mitragyna", "ketum", "kratom tea"], "cat": "other",
     "base": ["Stimulant-like at low amounts, opioid-like at higher ones; sedation and nausea are the usual field picture. Regular users can be physically dependent — sudden stopping adds withdrawal to the mix."], "tpl": ["CNSDEP"]},
    {"id": "caffeine", "name": "Caffeine / energy drinks", "aliases": ["coffee", "energy drink", "red bull"], "cat": "stimulant",
     "base": ["Masks fatigue and adds cardiovascular load on top of stimulants."]},
]

MEDS = [
    {"id": "ssri", "name": "SSRI antidepressants", "ex": "sertraline (Zoloft), escitalopram (Lexapro, Cipralex), citalopram, fluoxetine (Prozac), paroxetine", "grp": "Antidepressants"},
    {"id": "snri", "name": "SNRI antidepressants", "ex": "venlafaxine (Effexor), duloxetine (Cymbalta)", "grp": "Antidepressants"},
    {"id": "tca", "name": "Tricyclic antidepressants", "ex": "amitriptyline, clomipramine (Anafranil), nortriptyline", "grp": "Antidepressants"},
    {"id": "maoi", "name": "MAOI antidepressants", "ex": "moclobemide, tranylcypromine (Parnate), phenelzine (Nardil), selegiline", "grp": "Antidepressants"},
    {"id": "bupropion", "name": "Bupropion", "ex": "Wellbutrin, Zyban", "grp": "Antidepressants"},
    {"id": "sedad", "name": "Sedating antidepressants", "ex": "trazodone, mirtazapine (Remeron)", "grp": "Antidepressants"},
    {"id": "lithium", "name": "Lithium", "ex": "lithium carbonate", "grp": "Mood stabilizers"},
    {"id": "antipsych", "name": "Antipsychotics", "ex": "quetiapine (Seroquel), olanzapine (Zyprexa), risperidone, aripiprazole (Abilify)", "grp": "Mood stabilizers"},
    {"id": "anticonv", "name": "Anticonvulsants / mood stabilizers", "ex": "lamotrigine (Lamictal), valproate (Depakote), carbamazepine (Tegretol)", "grp": "Mood stabilizers"},
    {"id": "adhd-stim", "name": "ADHD stimulants", "ex": "methylphenidate (Ritalin, Concerta), lisdexamfetamine (Vyvanse, Elvanse), amphetamine salts (Adderall)", "grp": "ADHD"},
    {"id": "atomoxetine", "name": "Atomoxetine", "ex": "Strattera", "grp": "ADHD"},
    {"id": "benzo-rx", "name": "Benzodiazepines (prescribed)", "ex": "alprazolam (Xanax), diazepam (Valium), clonazepam (Klonopin, Rivotril), lorazepam (Ativan), bromazepam", "grp": "Sleep & anxiety"},
    {"id": "z-drug", "name": "Z-drugs (sleep)", "ex": "zolpidem (Ambien, Stilnox), zopiclone (Imovane), eszopiclone", "grp": "Sleep & anxiety"},
    {"id": "melatonin", "name": "Melatonin", "ex": "Circadin, OTC melatonin", "grp": "Sleep & anxiety"},
    {"id": "pregabalin", "name": "Gabapentinoids", "ex": "pregabalin (Lyrica), gabapentin (Neurontin)", "grp": "Sleep & anxiety"},
    {"id": "antihist-sed", "name": "Sedating antihistamines", "ex": "diphenhydramine (Benadryl), promethazine (Phenergan), hydroxyzine (Atarax), doxylamine", "grp": "Allergy"},
    {"id": "antihist-nonsed", "name": "Non-sedating antihistamines", "ex": "cetirizine (Zyrtec), loratadine (Claritin), levocetirizine, desloratadine, fexofenadine (Allegra)", "grp": "Allergy"},
    {"id": "tramadol", "name": "Tramadol", "ex": "Ultram, Tramal; combination products with paracetamol", "grp": "Pain"},
    {"id": "opioid-rx", "name": "Opioid painkillers (prescribed)", "ex": "codeine, oxycodone (OxyContin), morphine, fentanyl patches", "grp": "Pain"},
    {"id": "beta-blocker", "name": "Beta-blockers", "ex": "metoprolol, bisoprolol, propranolol, atenolol", "grp": "Heart & blood pressure"},
    {"id": "antihyp", "name": "Other blood-pressure meds", "ex": "ramipril, lisinopril, losartan, amlodipine, hydrochlorothiazide/indapamide (diuretics)", "grp": "Heart & blood pressure"},
    {"id": "diabetes", "name": "Diabetes medication", "ex": "insulin, metformin (Glucophage), gliclazide, glipizide", "grp": "Other long-term"},
    {"id": "asthma", "name": "Asthma inhalers", "ex": "salbutamol/albuterol (Ventolin), formoterol combinations (Symbicort)", "grp": "Other long-term"},
    {"id": "contraception", "name": "Hormonal contraception", "ex": "combined pill, mini-pill, patch, ring", "grp": "Other long-term"},
    {"id": "pde5", "name": "Erectile dysfunction meds", "ex": "sildenafil (Viagra), tadalafil (Cialis)", "grp": "Other long-term"},
    {"id": "sjw", "name": "St John's Wort", "ex": "hypericum extract — OTC herbal antidepressant", "grp": "Other long-term"},
]

# Personal factors: each has a base note (always shown when selected) and optional
# triggers that fire against selected substances/meds and produce risk cards.
# trigger.when: {"subs":[ids], "cats":[categories], "meds":[ids], "any": true}
FACTORS = [
    {"id": "under18", "label": "Under 18", "grp": "Age & body",
     "note": "Minors are hit harder by the same amounts, and you carry a duty of care. Involve on-site medics earlier than you would for an adult.",
     "triggers": [{"when": {"any": True}, "risk": "high", "ev": "est",
                   "note": "Any substance in a minor: escalate earlier than you would for an adult, keep them with the team, involve medics at the first warning sign."}]},
    {"id": "over50", "label": "Over ~50", "grp": "Age & body",
     "note": "Cardiovascular reserve declines with age; undiagnosed heart or blood-pressure conditions are common.",
     "triggers": [{"when": {"cats": ["stimulant"]}, "risk": "high", "ev": "est", "tpl": ["CARDIO"],
                   "note": "Stimulants at this age carry meaningfully higher cardiac-event risk — take palpitations and chest discomfort seriously immediately."}]},
    {"id": "lowweight", "label": "Low body weight (<60 kg)", "grp": "Age & body",
     "note": "Standard street doses act like high doses. Effects arrive faster and last longer.",
     "triggers": [{"when": {"subs": ["mdma"]}, "risk": "high", "ev": "est", "tpl": ["HYPERTHERMIA"],
                   "note": "Low body weight raises MDMA exposure per dose AND hyponatremia risk from water-drinking — fluid advice matters double."},
                  {"when": {"cats": ["depressant"]}, "risk": "caution", "ev": "est", "tpl": ["CNSDEP"],
                   "note": "Depressant doses overshoot easily at low body weight — watch sedation depth."}]},
    {"id": "female", "label": "Female", "grp": "Age & body",
     "note": "Lower average body water: higher exposure per dose for alcohol and MDMA.",
     "triggers": [{"when": {"subs": ["mdma"]}, "risk": "caution", "ev": "est", "tpl": ["HYPERTHERMIA"],
                   "note": "MDMA-related hyponatremia occurs disproportionately in women — keep plain-water intake at sips, prefer electrolytes."}]},
    {"id": "pregnancy", "label": "Pregnant / possibly", "grp": "Age & body",
     "note": "Every substance on this list carries fetal risk; the priority is the person in front of you.",
     "triggers": [{"when": {"any": True}, "risk": "high", "ev": "est",
                   "note": "Pregnancy + any substance: get medics involved early, and tell them about the pregnancy — it changes their treatment choices."}]},
    {"id": "heart", "label": "Heart condition / hypertension", "grp": "Health history",
     "note": "Known cardiac condition or high blood pressure — the main modifier for every stimulant.",
     "triggers": [{"when": {"cats": ["stimulant"]}, "risk": "danger", "ev": "est", "tpl": ["CARDIO"],
                   "note": "Stimulants on a known heart condition: treat chest pain, irregular pulse or breathlessness as an emergency, not a comedown."},
                  {"when": {"subs": ["ketamine"]}, "risk": "caution", "ev": "est", "tpl": ["CARDIO"],
                   "note": "Ketamine raises blood pressure and heart rate transiently."}]},
    {"id": "epilepsy", "label": "Epilepsy / prior seizures", "grp": "Health history",
     "note": "Seizure threshold is the axis to watch: sleep loss, stimulants, and missed anticonvulsant doses all lower it.",
     "triggers": [{"when": {"cats": ["stimulant"], "subs": ["dxm", "alcohol", "synth-cann", "kratom"]}, "risk": "high", "ev": "est", "tpl": ["SEIZURE"],
                   "note": "Stimulants, DXM, alcohol (especially wearing off), synthetic cannabinoids and kratom all make seizures more likely on top of epilepsy."}]},
    {"id": "psych", "label": "Psychosis history", "grp": "Health history",
     "note": "Personal or strong family history of psychosis or bipolar disorder.",
     "triggers": [{"when": {"cats": ["psychedelic", "stimulant"], "subs": ["cannabis", "synth-cann"]}, "risk": "high", "ev": "est", "tpl": ["PSYCH"],
                   "note": "Psychedelics, stimulants and high-THC cannabis can trigger or worsen psychotic episodes in vulnerable people; episodes may not settle when the drug wears off."}]},
    {"id": "sleepdep", "label": "Awake >24 h", "grp": "Current state",
     "note": "Sleep deprivation amplifies everything: seizure risk, psychosis risk, emotional instability, misjudged doses.",
     "triggers": [{"when": {"cats": ["stimulant"]}, "risk": "high", "ev": "est", "tpl": ["PSYCH", "SEIZURE"],
                   "note": "Stimulants past 24 h awake: paranoia and stimulant psychosis territory; persuading them to rest beats any other intervention."},
                  {"when": {"cats": ["psychedelic"]}, "risk": "caution", "ev": "case", "tpl": ["PSYCH"],
                   "note": "Exhaustion makes difficult trips much more likely."}]},
    {"id": "nofood", "label": "Not eaten today", "grp": "Current state",
     "note": "Empty stomach: faster, harder alcohol absorption and blood-sugar dips that mimic intoxication.",
     "triggers": [{"when": {"subs": ["alcohol"]}, "risk": "caution", "ev": "est",
                   "note": "Alcohol on an empty stomach peaks fast — reassess sedation 30–60 min after the last drink; get food in if cooperative."},
                  {"when": {"cats": ["stimulant"]}, "risk": "caution", "ev": "est",
                   "note": "Stimulants suppress appetite on top of an empty stomach — weakness, shakiness and collapse late in the night are often just glucose."}]},
    {"id": "dehydrated", "label": "Little fluid today", "grp": "Current state",
     "note": "Dehydration worsens overheating, comedowns, and lithium levels (if they take it).",
     "triggers": [{"when": {"subs": ["mdma", "amphetamine", "alcohol"]}, "risk": "caution", "ev": "est", "tpl": ["HYPERTHERMIA"],
                   "note": "Dehydration + stimulants/alcohol in a hot crowd: start electrolyte sips now, not when symptoms show."}]},
    {"id": "overhydrated", "label": "Drinking lots of plain water", "grp": "Current state",
     "note": "Litres of plain water without electrolytes is a risk in itself with MDMA (hyponatremia).",
     "triggers": [{"when": {"subs": ["mdma"]}, "risk": "high", "ev": "est", "tpl": ["HYPERTHERMIA"],
                   "note": "MDMA + heavy plain-water intake is the classic hyponatremia setup: confusion, headache, vomiting after 'doing everything right'. Switch to electrolytes, cap intake, watch closely."}]},
    {"id": "firsttime", "label": "First time with this substance", "grp": "Current state",
     "note": "Unknown individual sensitivity: effects, duration and side effects are unpredictable the first time.",
     "triggers": [{"when": {"any": True}, "risk": "caution", "ev": "est",
                   "note": "First use: advise starting with a fraction of a usual dose, waiting the full onset time before any redose, and staying near the team."}]},
]

# Mechanism templates: watch-for symptoms, DO-NOT list, supportive care, escalation threshold.
TEMPLATES = {
    "SS": {
        "name": "Serotonin syndrome risk",
        "watch": ["Restlessness, agitation, racing heart", "Tremor, muscle twitching or jerking (especially legs)", "Heavy sweating, rising temperature", "Confusion; in severe cases rigid muscles and temperature over 39 °C"],
        "donot": ["Do NOT let them take anything else serotonergic — no MDMA redose, no tramadol, no DXM cough medicine, no St John's Wort", "Do NOT wrap them in blankets or warm them if hot", "Do NOT give their next antidepressant dose 'to balance it out'"],
        "care": ["Cool, quiet space; remove excess clothing", "Small sips of water or electrolyte drink", "Stay with them — this can escalate over 1–6 hours"],
        "call": "Muscle rigidity, temperature over 39 °C / hot to touch, confusion or seizure → call emergency services (112) immediately."
    },
    "CNSDEP": {
        "name": "CNS / breathing depression risk",
        "watch": ["Heavy sedation, can't stay awake", "Slow, shallow or irregular breathing; snoring or gurgling sounds", "Blue-tinged lips or fingertips", "Unresponsive to voice or pain"],
        "donot": ["Do NOT give any more sedatives — no benzos (Xanax, Valium), no sleep meds (zolpidem), no alcohol, no sedating antihistamines (Benadryl, Phenergan)", "Do NOT leave them alone to 'sleep it off'", "Do NOT give coffee or stimulants to 'wake them up'", "Do NOT induce vomiting"],
        "care": ["Recovery position, keep airway clear", "Check breathing every 2–3 minutes — count breaths", "Keep trying to rouse them regularly"],
        "call": "Breathing under ~10/min, gaps in breathing, blue lips, or can't be woken → call 112 now. If opioids are involved and your team carries naloxone, use it per your protocol."
    },
    "CARDIO": {
        "name": "Cardiovascular strain",
        "watch": ["Chest pain or pressure", "Very fast (>140 at rest) or irregular pulse", "Severe sudden headache", "Breathlessness, fainting, pale/clammy skin"],
        "donot": ["Do NOT allow more stimulants — including energy drinks and coffee", "Do NOT give the person's own beta-blocker or any heart medication to 'slow the heart' — that is a medical decision only", "Do NOT put them in a cold shower (shock risk) — cool gradually"],
        "care": ["Calm, quiet, cool space; seated position", "Slow breathing together (in 4 s, out 6 s) for panic-driven tachycardia"],
        "call": "Chest pain lasting more than a few minutes, irregular pulse, fainting, or one-sided weakness/face droop → call 112."
    },
    "HYPERTHERMIA": {
        "name": "Overheating & fluid balance",
        "watch": ["Temperature rising, skin hot to touch", "Stopped sweating despite dancing", "Confusion, stumbling", "No urination for many hours, or drinking litres of plain water"],
        "donot": ["Do NOT push large volumes of plain water — hyponatremia kills MDMA users; ~500 ml/h sipped, ideally with electrolytes", "Do NOT let them keep dancing through warning signs", "Do NOT use alcohol to cool down or rehydrate"],
        "care": ["Shade / chill-out, cool-down breaks every 30–45 min of dancing", "Electrolyte drink in small sips", "Cool neck, armpits, groin with damp cloth if overheated"],
        "call": "Temperature over ~39 °C, hot dry skin, confusion, collapse, or headache + vomiting + confusion after drinking lots of water (possible hyponatremia) → 112."
    },
    "SEIZURE": {
        "name": "Seizure risk",
        "watch": ["Muscle twitching or jerks", "Complaints of strange aura, déjà vu, metallic taste", "Sudden unresponsive staring"],
        "donot": ["Do NOT restrain a seizing person", "Do NOT put anything in their mouth"],
        "care": ["Clear hard objects away, cushion the head", "Time the seizure", "Recovery position once it stops"],
        "call": "Any seizure in this context warrants 112; a seizure lasting over 5 minutes or repeating is a critical emergency."
    },
    "HTN": {
        "name": "Hypertensive crisis risk",
        "watch": ["Sudden severe ('thunderclap') headache", "Stiff neck, nosebleed", "Chest pain, vomiting", "Visual disturbance"],
        "donot": ["Do NOT give any medication to lower blood pressure yourself", "Do NOT allow any further stimulants or tyramine-rich food/drink (aged cheese, tap beer, red wine)"],
        "care": ["Sit them upright, calm environment", "Continuous observation"],
        "call": "This combination can raise blood pressure to stroke levels — with a severe sudden headache or chest pain, call 112 immediately."
    },
    "PSYCH": {
        "name": "Psychological distress",
        "watch": ["Escalating anxiety, paranoia", "Losing touch with surroundings", "Talk of harming self or others"],
        "donot": ["Do NOT argue with delusions or 'logic them out' of the trip", "Do NOT leave them alone", "Do NOT allow more psychedelics or stimulants to 'fix' it"],
        "care": ["One calm sitter, quiet dim space", "Grounding: name, place, 'this is a substance, it will pass'", "Water, blanket, time"],
        "call": "Danger to self or others, or psychosis not settling as the drug should wear off → medical/psychiatric help."
    },
    "HYPOGLY": {
        "name": "Blood sugar risk",
        "watch": ["Confusion, aggression, slurred speech that looks like drunkenness", "Sweating, shakiness, pallor", "Drowsiness progressing to unconsciousness"],
        "donot": ["Do NOT assume a diabetic who seems drunk is just drunk — check if they can test glucose", "Do NOT give insulin", "Do NOT force food or drink into an unconscious person"],
        "care": ["If conscious and cooperative: sugary drink or food, then something starchy", "Help them test blood sugar if they have a meter"],
        "call": "Unconscious or not improving within 10–15 minutes of sugar → 112."
    },
}
